wireplumber.settings = {
    node.restore-default-targets = false
    linking.follow-default-target = true
}

monitor.alsa.rules = [
    {
        matches = [
            {
                node.name = "~alsa_output.*"
            }
        ]
        actions = {
            update-props = {
                priority.session = 2000
            }
        }
    }
    {
        matches = [
            {
                node.description = "Ryzen HD Audio Controller Speaker"
            }
        ]
        actions = {
            update-props = {
                priority.session = 100
            }
        }
    }
]

monitor.bluez.rules = [
    {
        matches = [
            {
                node.name = "~bluez_output.*"
            }
        ]
        actions = {
            update-props = {
                priority.session = 2000
            }
        }
    }
]
