# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  paging:
    colorArg: always
    pager: delta --dark --color-only --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  commitPrefix:
    pattern: "^(\\d+)-.*$"
    replace: "[#$1] "
gui:
  border: single
  nerdFontsVersion: "3"

customCommands:
  - key: "<c-o>"
    context: localBranches
    description: Open merge request
    command: >
      REPO=$(echo "{{ index .SelectedRemote.Urls 0 }}" | awk -F: '{print $2}' | sed 's/\.git$//') &&
      xdg-open "https://dev.antmicro.com/git/repositories/${REPO}/merge_requests/new?merge_request%5Bsource_branch%5D={{ .SelectedLocalBranch.Name }}&merge_request%5Btarget_branch%5D=main"
  - key: "i"
    context: localBranches
    description: Open issue in browser
    command: >
      ISSUE=$(echo "{{ .SelectedLocalBranch.Name }}" | awk -F'-' '{print $1}') &&
      xdg-open "https://dev.antmicro.com/issues/${ISSUE}"
  - key: "i"
    context: commits
    description: Open issue in browser
    command: >
      ISSUE=$(echo "{{ .SelectedCommit.Name }}" | awk -F'[ #]' '{print $2}') &&
      xdg-open "https://dev.antmicro.com/issues/${ISSUE}"
