# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

# https://github.com/alacritty/alacritty/tree/master#configuration

[window]

padding.x = 10
padding.y = 10

decorations = "Full"

[font]

normal.family = "JetBrains Mono"
normal.style = "Medium"
bold.family = "JetBrains Mono"
bold.style = "Bold"
italic.family = "JetBrains Mono"
italic.style = "Italic"
bold_italic.family = "JetBrains Mono"
bold_italic.style = "BoldItalic"

size = 16.0

